name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3.5.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/light-snake-animation.svg
            assets/dark-snake-animation.svg?color_snake=orange&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake contribution grid"
          file_pattern: "assets/*.svg"